pub use crate::dispatch::identify;

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum CommandId {
    Unknown,
    Auth,
    Hello,
    Client,
    Command,
    Select,
    Quit,
    Ping,
    Echo,
    Eval,
    EvalRo,
    EvalSha,
    EvalShaRo,
    Script,
    Del,
    Exists,
    Touch,
    Unlink,
    Type,
    Rename,
    RenameNx,
    DbSize,
    Keys,
    Scan,
    Move,
    Dump,
    Restore,
    Sort,
    Copy,
    FlushDb,
    FlushAll,
    Expire,
    PExpire,
    ExpireAt,
    PExpireAt,
    Persist,
    Ttl,
    PTtl,
    Get,
    Set,
    SetNx,
    GetSet,
    GetDel,
    SetEx,
    PSetEx,
    GetEx,
    Delex,
    Digest,
    Append,
    SubStr,
    StrLen,
    SetRange,
    GetRange,
    Lcs,
    MGet,
    MSet,
    MSetEx,
    MSetNx,
    Incr,
    IncrBy,
    IncrByFloat,
    Decr,
    DecrBy,
    SetBit,
    GetBit,
    BitCount,
    BitPos,
    BitOp,
    BitField,
    BitFieldRo,
    PfAdd,
    PfCount,
    PfMerge,
    HSet,
    HMSet,
    HSetNx,
    HGet,
    HMGet,
    HGetAll,
    HDel,
    HExists,
    HKeys,
    HVals,
    HLen,
    HStrLen,
    HIncrBy,
    HIncrByFloat,
    HScan,
    HRandField,
    LPush,
    LPushX,
    RPush,
    RPushX,
    LPop,
    RPop,
    LRem,
    LLen,
    LIndex,
    LRange,
    LSet,
    LTrim,
    LInsert,
    LPos,
    LMove,
    LMPop,
    BLPop,
    BRPop,
    BLMPop,
    BRPopLPush,
    RPopLPush,
    SAdd,
    SRem,
    SMembers,
    SCard,
    SMove,
    SPop,
    SInter,
    SUnion,
    SDiff,
    SScan,
    SIsMember,
    SMIsMember,
    SDiffStore,
    SInterCard,
    SInterStore,
    SUnionStore,
    SRandMember,
    ZAdd,
    ZRem,
    ZCard,
    ZCount,
    ZScore,
    ZRank,
    ZRevRank,
    ZIncrBy,
    ZMScore,
    ZRange,
    ZRevRange,
    ZPopMin,
    ZPopMax,
    BZPopMin,
    BZPopMax,
    ZMPop,
    BZMPop,
    ZInter,
    ZInterStore,
    ZUnion,
    ZUnionStore,
    ZDiff,
    ZDiffStore,
    ZScan,
    ZRandMember,
    ZRangeStore,
    ZRangeByScore,
    ZRangeByLex,
    ZRevRangeByScore,
    ZRevRangeByLex,
    ZLexCount,
    ZRemRangeByLex,
    ZRemRangeByRank,
    ZRemRangeByScore,
    GeoAdd,
    GeoPos,
    GeoDist,
    GeoHash,
    GeoRadius,
    GeoRadiusRo,
    GeoSearch,
    GeoSearchStore,
    GeoRadiusByMember,
    GeoRadiusByMemberRo,
    XAdd,
    XLen,
    XDel,
    XRange,
    XRevRange,
    XTrim,
    XRead,
    XGroup,
    XAck,
    XClaim,
    XPending,
    XReadGroup,
    XAutoClaim,
    JsonArrAppend,
    JsonArrIndex,
    JsonArrInsert,
    JsonArrLen,
    JsonArrPop,
    JsonArrTrim,
    JsonClear,
    JsonDebug,
    JsonDel,
    JsonForget,
    JsonGet,
    JsonMerge,
    JsonMGet,
    JsonMSet,
    JsonNumIncrBy,
    JsonNumMultBy,
    JsonObjKeys,
    JsonObjLen,
    JsonResp,
    JsonSet,
    JsonStrAppend,
    JsonStrLen,
    JsonToggle,
    JsonType,
    Acl,
    Config,
    Publish,
    Subscribe,
    Unsubscribe,
    PSubscribe,
    PUnsubscribe,
    PubSub,
    Multi,
    Exec,
    Discard,
    Watch,
    Unwatch,
}

impl CommandId {
    #[inline(always)]
    pub fn name(self) -> Option<&'static str> {
        Some(match self {
            Self::Unknown => return None,
            Self::Auth => "AUTH",
            Self::Hello => "HELLO",
            Self::Client => "CLIENT",
            Self::Command => "COMMAND",
            Self::Select => "SELECT",
            Self::Quit => "QUIT",
            Self::Ping => "PING",
            Self::Echo => "ECHO",
            Self::Eval => "EVAL",
            Self::EvalRo => "EVAL_RO",
            Self::EvalSha => "EVALSHA",
            Self::EvalShaRo => "EVALSHA_RO",
            Self::Script => "SCRIPT",
            Self::Del => "DEL",
            Self::Exists => "EXISTS",
            Self::Touch => "TOUCH",
            Self::Unlink => "UNLINK",
            Self::Type => "TYPE",
            Self::Rename => "RENAME",
            Self::RenameNx => "RENAMENX",
            Self::DbSize => "DBSIZE",
            Self::Keys => "KEYS",
            Self::Scan => "SCAN",
            Self::Move => "MOVE",
            Self::Dump => "DUMP",
            Self::Restore => "RESTORE",
            Self::Sort => "SORT",
            Self::Copy => "COPY",
            Self::FlushDb => "FLUSHDB",
            Self::FlushAll => "FLUSHALL",
            Self::Expire => "EXPIRE",
            Self::PExpire => "PEXPIRE",
            Self::ExpireAt => "EXPIREAT",
            Self::PExpireAt => "PEXPIREAT",
            Self::Persist => "PERSIST",
            Self::Ttl => "TTL",
            Self::PTtl => "PTTL",
            Self::Get => "GET",
            Self::Set => "SET",
            Self::SetNx => "SETNX",
            Self::GetSet => "GETSET",
            Self::GetDel => "GETDEL",
            Self::SetEx => "SETEX",
            Self::PSetEx => "PSETEX",
            Self::GetEx => "GETEX",
            Self::Delex => "DELEX",
            Self::Digest => "DIGEST",
            Self::Append => "APPEND",
            Self::SubStr => "SUBSTR",
            Self::StrLen => "STRLEN",
            Self::SetRange => "SETRANGE",
            Self::GetRange => "GETRANGE",
            Self::Lcs => "LCS",
            Self::MGet => "MGET",
            Self::MSet => "MSET",
            Self::MSetEx => "MSETEX",
            Self::MSetNx => "MSETNX",
            Self::Incr => "INCR",
            Self::IncrBy => "INCRBY",
            Self::IncrByFloat => "INCRBYFLOAT",
            Self::Decr => "DECR",
            Self::DecrBy => "DECRBY",
            Self::SetBit => "SETBIT",
            Self::GetBit => "GETBIT",
            Self::BitCount => "BITCOUNT",
            Self::BitPos => "BITPOS",
            Self::BitOp => "BITOP",
            Self::BitField => "BITFIELD",
            Self::BitFieldRo => "BITFIELD_RO",
            Self::PfAdd => "PFADD",
            Self::PfCount => "PFCOUNT",
            Self::PfMerge => "PFMERGE",
            Self::HSet => "HSET",
            Self::HMSet => "HMSET",
            Self::HSetNx => "HSETNX",
            Self::HGet => "HGET",
            Self::HMGet => "HMGET",
            Self::HGetAll => "HGETALL",
            Self::HDel => "HDEL",
            Self::HExists => "HEXISTS",
            Self::HKeys => "HKEYS",
            Self::HVals => "HVALS",
            Self::HLen => "HLEN",
            Self::HStrLen => "HSTRLEN",
            Self::HIncrBy => "HINCRBY",
            Self::HIncrByFloat => "HINCRBYFLOAT",
            Self::HScan => "HSCAN",
            Self::HRandField => "HRANDFIELD",
            Self::LPush => "LPUSH",
            Self::LPushX => "LPUSHX",
            Self::RPush => "RPUSH",
            Self::RPushX => "RPUSHX",
            Self::LPop => "LPOP",
            Self::RPop => "RPOP",
            Self::LRem => "LREM",
            Self::LLen => "LLEN",
            Self::LIndex => "LINDEX",
            Self::LRange => "LRANGE",
            Self::LSet => "LSET",
            Self::LTrim => "LTRIM",
            Self::LInsert => "LINSERT",
            Self::LPos => "LPOS",
            Self::LMove => "LMOVE",
            Self::LMPop => "LMPOP",
            Self::BLPop => "BLPOP",
            Self::BRPop => "BRPOP",
            Self::BLMPop => "BLMPOP",
            Self::BRPopLPush => "BRPOPLPUSH",
            Self::RPopLPush => "RPOPLPUSH",
            Self::SAdd => "SADD",
            Self::SRem => "SREM",
            Self::SMembers => "SMEMBERS",
            Self::SCard => "SCARD",
            Self::SMove => "SMOVE",
            Self::SPop => "SPOP",
            Self::SInter => "SINTER",
            Self::SUnion => "SUNION",
            Self::SDiff => "SDIFF",
            Self::SScan => "SSCAN",
            Self::SIsMember => "SISMEMBER",
            Self::SMIsMember => "SMISMEMBER",
            Self::SDiffStore => "SDIFFSTORE",
            Self::SInterCard => "SINTERCARD",
            Self::SInterStore => "SINTERSTORE",
            Self::SUnionStore => "SUNIONSTORE",
            Self::SRandMember => "SRANDMEMBER",
            Self::ZAdd => "ZADD",
            Self::ZRem => "ZREM",
            Self::ZCard => "ZCARD",
            Self::ZCount => "ZCOUNT",
            Self::ZScore => "ZSCORE",
            Self::ZRank => "ZRANK",
            Self::ZRevRank => "ZREVRANK",
            Self::ZIncrBy => "ZINCRBY",
            Self::ZMScore => "ZMSCORE",
            Self::ZRange => "ZRANGE",
            Self::ZRevRange => "ZREVRANGE",
            Self::ZPopMin => "ZPOPMIN",
            Self::ZPopMax => "ZPOPMAX",
            Self::BZPopMin => "BZPOPMIN",
            Self::BZPopMax => "BZPOPMAX",
            Self::ZMPop => "ZMPOP",
            Self::BZMPop => "BZMPOP",
            Self::ZInter => "ZINTER",
            Self::ZInterStore => "ZINTERSTORE",
            Self::ZUnion => "ZUNION",
            Self::ZUnionStore => "ZUNIONSTORE",
            Self::ZDiff => "ZDIFF",
            Self::ZDiffStore => "ZDIFFSTORE",
            Self::ZScan => "ZSCAN",
            Self::ZRandMember => "ZRANDMEMBER",
            Self::ZRangeStore => "ZRANGESTORE",
            Self::ZRangeByScore => "ZRANGEBYSCORE",
            Self::ZRangeByLex => "ZRANGEBYLEX",
            Self::ZRevRangeByScore => "ZREVRANGEBYSCORE",
            Self::ZRevRangeByLex => "ZREVRANGEBYLEX",
            Self::ZLexCount => "ZLEXCOUNT",
            Self::ZRemRangeByLex => "ZREMRANGEBYLEX",
            Self::ZRemRangeByRank => "ZREMRANGEBYRANK",
            Self::ZRemRangeByScore => "ZREMRANGEBYSCORE",
            Self::GeoAdd => "GEOADD",
            Self::GeoPos => "GEOPOS",
            Self::GeoDist => "GEODIST",
            Self::GeoHash => "GEOHASH",
            Self::GeoRadius => "GEORADIUS",
            Self::GeoRadiusRo => "GEORADIUS_RO",
            Self::GeoSearch => "GEOSEARCH",
            Self::GeoSearchStore => "GEOSEARCHSTORE",
            Self::GeoRadiusByMember => "GEORADIUSBYMEMBER",
            Self::GeoRadiusByMemberRo => "GEORADIUSBYMEMBER_RO",
            Self::XAdd => "XADD",
            Self::XLen => "XLEN",
            Self::XDel => "XDEL",
            Self::XRange => "XRANGE",
            Self::XRevRange => "XREVRANGE",
            Self::XTrim => "XTRIM",
            Self::XRead => "XREAD",
            Self::XGroup => "XGROUP",
            Self::XAck => "XACK",
            Self::XClaim => "XCLAIM",
            Self::XPending => "XPENDING",
            Self::XReadGroup => "XREADGROUP",
            Self::XAutoClaim => "XAUTOCLAIM",
            Self::JsonArrAppend => "JSON.ARRAPPEND",
            Self::JsonArrIndex => "JSON.ARRINDEX",
            Self::JsonArrInsert => "JSON.ARRINSERT",
            Self::JsonArrLen => "JSON.ARRLEN",
            Self::JsonArrPop => "JSON.ARRPOP",
            Self::JsonArrTrim => "JSON.ARRTRIM",
            Self::JsonClear => "JSON.CLEAR",
            Self::JsonDebug => "JSON.DEBUG",
            Self::JsonDel => "JSON.DEL",
            Self::JsonForget => "JSON.FORGET",
            Self::JsonGet => "JSON.GET",
            Self::JsonMerge => "JSON.MERGE",
            Self::JsonMGet => "JSON.MGET",
            Self::JsonMSet => "JSON.MSET",
            Self::JsonNumIncrBy => "JSON.NUMINCRBY",
            Self::JsonNumMultBy => "JSON.NUMMULTBY",
            Self::JsonObjKeys => "JSON.OBJKEYS",
            Self::JsonObjLen => "JSON.OBJLEN",
            Self::JsonResp => "JSON.RESP",
            Self::JsonSet => "JSON.SET",
            Self::JsonStrAppend => "JSON.STRAPPEND",
            Self::JsonStrLen => "JSON.STRLEN",
            Self::JsonToggle => "JSON.TOGGLE",
            Self::JsonType => "JSON.TYPE",
            Self::Acl => "ACL",
            Self::Config => "CONFIG",
            Self::Publish => "PUBLISH",
            Self::Subscribe => "SUBSCRIBE",
            Self::Unsubscribe => "UNSUBSCRIBE",
            Self::PSubscribe => "PSUBSCRIBE",
            Self::PUnsubscribe => "PUNSUBSCRIBE",
            Self::PubSub => "PUBSUB",
            Self::Multi => "MULTI",
            Self::Exec => "EXEC",
            Self::Discard => "DISCARD",
            Self::Watch => "WATCH",
            Self::Unwatch => "UNWATCH",
        })
    }
}
