import * as path from "node:path";
import { defineConfig } from "@rspress/core";
import { pluginSitemap } from "@rspress/plugin-sitemap";

const commandSidebar = [
    {
        text: "Overview",
        items: [{ text: "Commands Reference", link: "/commands/" }],
    },
    {
        text: "Connection",
        collapsed: true,
        items: [
            { text: "AUTH", link: "/commands/auth" },
            { text: "CLIENT", link: "/commands/client" },
            { text: "ECHO", link: "/commands/echo" },
            { text: "HELLO", link: "/commands/hello" },
            { text: "PING", link: "/commands/ping" },
            { text: "QUIT", link: "/commands/quit" },
            { text: "SELECT", link: "/commands/select" },
        ],
    },
    {
        text: "Server",
        collapsed: true,
        items: [
            { text: "COMMAND", link: "/commands/command" },
            { text: "CONFIG", link: "/commands/config" },
            { text: "DBSIZE", link: "/commands/dbsize" },
            { text: "FLUSHALL", link: "/commands/flushall" },
            { text: "FLUSHDB", link: "/commands/flushdb" },
        ],
    },
    {
        text: "Keyspace",
        collapsed: true,
        items: [
            { text: "COPY", link: "/commands/copy" },
            { text: "DEL", link: "/commands/del" },
            { text: "DUMP", link: "/commands/dump" },
            { text: "EXISTS", link: "/commands/exists" },
            { text: "EXPIRE", link: "/commands/expire" },
            { text: "EXPIREAT", link: "/commands/expireat" },
            { text: "KEYS", link: "/commands/keys" },
            { text: "MOVE", link: "/commands/move" },
            { text: "OBJECT", link: "/commands/object" },
            { text: "PERSIST", link: "/commands/persist" },
            { text: "PEXPIRE", link: "/commands/pexpire" },
            { text: "PEXPIREAT", link: "/commands/pexpireat" },
            { text: "PTTL", link: "/commands/pttl" },
            { text: "RANDOMKEY", link: "/commands/randomkey" },
            { text: "RENAME", link: "/commands/rename" },
            { text: "RENAMENX", link: "/commands/renamenx" },
            { text: "RESTORE", link: "/commands/restore" },
            { text: "SCAN", link: "/commands/scan" },
            { text: "SORT", link: "/commands/sort" },
            { text: "TOUCH", link: "/commands/touch" },
            { text: "TTL", link: "/commands/ttl" },
            { text: "TYPE", link: "/commands/type" },
            { text: "UNLINK", link: "/commands/unlink" },
        ],
    },
    {
        text: "String",
        collapsed: true,
        items: [
            { text: "APPEND", link: "/commands/append" },
            { text: "BITCOUNT", link: "/commands/bitcount" },
            { text: "BITFIELD", link: "/commands/bitfield" },
            { text: "BITFIELD_RO", link: "/commands/bitfield-ro" },
            { text: "BITOP", link: "/commands/bitop" },
            { text: "BITPOS", link: "/commands/bitpos" },
            { text: "DECR", link: "/commands/decr" },
            { text: "DECRBY", link: "/commands/decrby" },
            { text: "DELEX", link: "/commands/delex" },
            { text: "DIGEST", link: "/commands/digest" },
            { text: "GET", link: "/commands/get" },
            { text: "GETBIT", link: "/commands/getbit" },
            { text: "GETDEL", link: "/commands/getdel" },
            { text: "GETEX", link: "/commands/getex" },
            { text: "GETRANGE", link: "/commands/getrange" },
            { text: "GETSET", link: "/commands/getset" },
            { text: "INCR", link: "/commands/incr" },
            { text: "INCRBY", link: "/commands/incrby" },
            { text: "INCRBYFLOAT", link: "/commands/incrbyfloat" },
            { text: "LCS", link: "/commands/lcs" },
            { text: "MGET", link: "/commands/mget" },
            { text: "MSET", link: "/commands/mset" },
            { text: "MSETEX", link: "/commands/msetex" },
            { text: "MSETNX", link: "/commands/msetnx" },
            { text: "PFADD", link: "/commands/pfadd" },
            { text: "PFCOUNT", link: "/commands/pfcount" },
            { text: "PFMERGE", link: "/commands/pfmerge" },
            { text: "PSETEX", link: "/commands/psetex" },
            { text: "SET", link: "/commands/set" },
            { text: "SETBIT", link: "/commands/setbit" },
            { text: "SETEX", link: "/commands/setex" },
            { text: "SETNX", link: "/commands/setnx" },
            { text: "SETRANGE", link: "/commands/setrange" },
            { text: "STRLEN", link: "/commands/strlen" },
            { text: "SUBSTR", link: "/commands/substr" },
        ],
    },
    {
        text: "Hash",
        collapsed: true,
        items: [
            { text: "HDEL", link: "/commands/hdel" },
            { text: "HEXISTS", link: "/commands/hexists" },
            { text: "HGET", link: "/commands/hget" },
            { text: "HGETALL", link: "/commands/hgetall" },
            { text: "HINCRBY", link: "/commands/hincrby" },
            { text: "HINCRBYFLOAT", link: "/commands/hincrbyfloat" },
            { text: "HKEYS", link: "/commands/hkeys" },
            { text: "HLEN", link: "/commands/hlen" },
            { text: "HMGET", link: "/commands/hmget" },
            { text: "HMSET", link: "/commands/hmset" },
            { text: "HRANDFIELD", link: "/commands/hrandfield" },
            { text: "HSCAN", link: "/commands/hscan" },
            { text: "HSET", link: "/commands/hset" },
            { text: "HSETNX", link: "/commands/hsetnx" },
            { text: "HSTRLEN", link: "/commands/hstrlen" },
            { text: "HVALS", link: "/commands/hvals" },
        ],
    },
    {
        text: "List",
        collapsed: true,
        items: [
            { text: "BLMPOP", link: "/commands/blmpop" },
            { text: "BLPOP", link: "/commands/blpop" },
            { text: "BRPOP", link: "/commands/brpop" },
            { text: "BRPOPLPUSH", link: "/commands/brpoplpush" },
            { text: "LINDEX", link: "/commands/lindex" },
            { text: "LINSERT", link: "/commands/linsert" },
            { text: "LLEN", link: "/commands/llen" },
            { text: "LMOVE", link: "/commands/lmove" },
            { text: "LMPOP", link: "/commands/lmpop" },
            { text: "LPOP", link: "/commands/lpop" },
            { text: "LPOS", link: "/commands/lpos" },
            { text: "LPUSH", link: "/commands/lpush" },
            { text: "LPUSHX", link: "/commands/lpushx" },
            { text: "LRANGE", link: "/commands/lrange" },
            { text: "LREM", link: "/commands/lrem" },
            { text: "LSET", link: "/commands/lset" },
            { text: "LTRIM", link: "/commands/ltrim" },
            { text: "RPOP", link: "/commands/rpop" },
            { text: "RPOPLPUSH", link: "/commands/rpoplpush" },
            { text: "RPUSH", link: "/commands/rpush" },
            { text: "RPUSHX", link: "/commands/rpushx" },
        ],
    },
    {
        text: "Set",
        collapsed: true,
        items: [
            { text: "SADD", link: "/commands/sadd" },
            { text: "SCARD", link: "/commands/scard" },
            { text: "SDIFF", link: "/commands/sdiff" },
            { text: "SDIFFSTORE", link: "/commands/sdiffstore" },
            { text: "SINTER", link: "/commands/sinter" },
            { text: "SINTERCARD", link: "/commands/sintercard" },
            { text: "SINTERSTORE", link: "/commands/sinterstore" },
            { text: "SISMEMBER", link: "/commands/sismember" },
            { text: "SMEMBERS", link: "/commands/smembers" },
            { text: "SMISMEMBER", link: "/commands/smismember" },
            { text: "SMOVE", link: "/commands/smove" },
            { text: "SPOP", link: "/commands/spop" },
            { text: "SRANDMEMBER", link: "/commands/srandmember" },
            { text: "SREM", link: "/commands/srem" },
            { text: "SSCAN", link: "/commands/sscan" },
            { text: "SUNION", link: "/commands/sunion" },
            { text: "SUNIONSTORE", link: "/commands/sunionstore" },
        ],
    },
    {
        text: "Sorted Set",
        collapsed: true,
        items: [
            { text: "BZMPOP", link: "/commands/bzmpop" },
            { text: "BZPOPMAX", link: "/commands/bzpopmax" },
            { text: "BZPOPMIN", link: "/commands/bzpopmin" },
            { text: "ZADD", link: "/commands/zadd" },
            { text: "ZCARD", link: "/commands/zcard" },
            { text: "ZCOUNT", link: "/commands/zcount" },
            { text: "ZDIFF", link: "/commands/zdiff" },
            { text: "ZDIFFSTORE", link: "/commands/zdiffstore" },
            { text: "ZINCRBY", link: "/commands/zincrby" },
            { text: "ZINTER", link: "/commands/zinter" },
            { text: "ZINTERSTORE", link: "/commands/zinterstore" },
            { text: "ZLEXCOUNT", link: "/commands/zlexcount" },
            { text: "ZMPOP", link: "/commands/zmpop" },
            { text: "ZMSCORE", link: "/commands/zmscore" },
            { text: "ZPOPMAX", link: "/commands/zpopmax" },
            { text: "ZPOPMIN", link: "/commands/zpopmin" },
            { text: "ZRANDMEMBER", link: "/commands/zrandmember" },
            { text: "ZRANGE", link: "/commands/zrange" },
            { text: "ZRANGEBYLEX", link: "/commands/zrangebylex" },
            { text: "ZRANGEBYSCORE", link: "/commands/zrangebyscore" },
            { text: "ZRANGESTORE", link: "/commands/zrangestore" },
            { text: "ZRANK", link: "/commands/zrank" },
            { text: "ZREM", link: "/commands/zrem" },
            { text: "ZREMRANGEBYLEX", link: "/commands/zremrangebylex" },
            { text: "ZREMRANGEBYRANK", link: "/commands/zremrangebyrank" },
            { text: "ZREMRANGEBYSCORE", link: "/commands/zremrangebyscore" },
            { text: "ZREVRANGE", link: "/commands/zrevrange" },
            { text: "ZREVRANGEBYLEX", link: "/commands/zrevrangebylex" },
            { text: "ZREVRANGEBYSCORE", link: "/commands/zrevrangebyscore" },
            { text: "ZREVRANK", link: "/commands/zrevrank" },
            { text: "ZSCAN", link: "/commands/zscan" },
            { text: "ZSCORE", link: "/commands/zscore" },
            { text: "ZUNION", link: "/commands/zunion" },
            { text: "ZUNIONSTORE", link: "/commands/zunionstore" },
        ],
    },
    {
        text: "Geo",
        collapsed: true,
        items: [
            { text: "GEOADD", link: "/commands/geoadd" },
            { text: "GEODIST", link: "/commands/geodist" },
            { text: "GEOHASH", link: "/commands/geohash" },
            { text: "GEOPOS", link: "/commands/geopos" },
            { text: "GEORADIUS", link: "/commands/georadius" },
            { text: "GEORADIUSBYMEMBER", link: "/commands/georadiusbymember" },
            { text: "GEORADIUSBYMEMBER_RO", link: "/commands/georadiusbymember-ro" },
            { text: "GEORADIUS_RO", link: "/commands/georadius-ro" },
            { text: "GEOSEARCH", link: "/commands/geosearch" },
            { text: "GEOSEARCHSTORE", link: "/commands/geosearchstore" },
        ],
    },
    {
        text: "Stream",
        collapsed: true,
        items: [
            { text: "XACK", link: "/commands/xack" },
            { text: "XADD", link: "/commands/xadd" },
            { text: "XAUTOCLAIM", link: "/commands/xautoclaim" },
            { text: "XCLAIM", link: "/commands/xclaim" },
            { text: "XDEL", link: "/commands/xdel" },
            { text: "XDELEX", link: "/commands/xdelex" },
            { text: "XGROUP", link: "/commands/xgroup" },
            { text: "XLEN", link: "/commands/xlen" },
            { text: "XPENDING", link: "/commands/xpending" },
            { text: "XRANGE", link: "/commands/xrange" },
            { text: "XREAD", link: "/commands/xread" },
            { text: "XREADGROUP", link: "/commands/xreadgroup" },
            { text: "XREVRANGE", link: "/commands/xrevrange" },
            { text: "XTRIM", link: "/commands/xtrim" },
        ],
    },
    {
        text: "Scripting",
        collapsed: true,
        items: [
            { text: "EVAL", link: "/commands/eval" },
            { text: "EVALSHA", link: "/commands/evalsha" },
            { text: "EVALSHA_RO", link: "/commands/evalsha-ro" },
            { text: "EVAL_RO", link: "/commands/eval-ro" },
            { text: "SCRIPT", link: "/commands/script" },
        ],
    },
    {
        text: "Transaction",
        collapsed: true,
        items: [
            { text: "DISCARD", link: "/commands/discard" },
            { text: "EXEC", link: "/commands/exec" },
            { text: "MULTI", link: "/commands/multi" },
            { text: "UNWATCH", link: "/commands/unwatch" },
            { text: "WATCH", link: "/commands/watch" },
        ],
    },
    {
        text: "Pub/Sub",
        collapsed: true,
        items: [
            { text: "PSUBSCRIBE", link: "/commands/psubscribe" },
            { text: "PUBLISH", link: "/commands/publish" },
            { text: "PUBSUB", link: "/commands/pubsub" },
            { text: "PUNSUBSCRIBE", link: "/commands/punsubscribe" },
            { text: "SPUBLISH", link: "/commands/spublish" },
            { text: "SSUBSCRIBE", link: "/commands/ssubscribe" },
            { text: "SUBSCRIBE", link: "/commands/subscribe" },
            { text: "SUNSUBSCRIBE", link: "/commands/sunsubscribe" },
            { text: "UNSUBSCRIBE", link: "/commands/unsubscribe" },
        ],
    },
    {
        text: "JSON",
        collapsed: true,
        items: [
            { text: "JSON.ARRAPPEND", link: "/commands/json-arrappend" },
            { text: "JSON.ARRINDEX", link: "/commands/json-arrindex" },
            { text: "JSON.ARRINSERT", link: "/commands/json-arrinsert" },
            { text: "JSON.ARRLEN", link: "/commands/json-arrlen" },
            { text: "JSON.ARRPOP", link: "/commands/json-arrpop" },
            { text: "JSON.ARRTRIM", link: "/commands/json-arrtrim" },
            { text: "JSON.CLEAR", link: "/commands/json-clear" },
            { text: "JSON.DEBUG", link: "/commands/json-debug" },
            { text: "JSON.DEL", link: "/commands/json-del" },
            { text: "JSON.FORGET", link: "/commands/json-forget" },
            { text: "JSON.GET", link: "/commands/json-get" },
            { text: "JSON.MERGE", link: "/commands/json-merge" },
            { text: "JSON.MGET", link: "/commands/json-mget" },
            { text: "JSON.MSET", link: "/commands/json-mset" },
            { text: "JSON.NUMINCRBY", link: "/commands/json-numincrby" },
            { text: "JSON.NUMMULTBY", link: "/commands/json-nummultby" },
            { text: "JSON.OBJKEYS", link: "/commands/json-objkeys" },
            { text: "JSON.OBJLEN", link: "/commands/json-objlen" },
            { text: "JSON.RESP", link: "/commands/json-resp" },
            { text: "JSON.SET", link: "/commands/json-set" },
            { text: "JSON.STRAPPEND", link: "/commands/json-strappend" },
            { text: "JSON.STRLEN", link: "/commands/json-strlen" },
            { text: "JSON.TOGGLE", link: "/commands/json-toggle" },
            { text: "JSON.TYPE", link: "/commands/json-type" },
        ],
    },
];

export default defineConfig({
    root: path.join(import.meta.dirname, "pages"),
    plugins: [
        pluginSitemap({
            siteUrl: "https://docs.betterkv.com",
        }),
    ],
    title: "BetterKV Docs",
    description:
        "The high-performance Redis-compatible key-value store. Lightning-fast, reliable, open-source.",
    icon: "/icon.svg",
    logo: {
        light: "/logo-light.svg",
        dark: "/logo-dark.svg",
    },
    globalStyles: path.join(import.meta.dirname, "styles", "global.css"),
    themeConfig: {
        footer: {
            message:
                "© 2026 BetterKV — Open-source, high-performance key-value store built in rust.",
        },
        socialLinks: [
            {
                icon: "github",
                mode: "link",
                content: "https://github.com/1jmdev/BetterKV",
            },
        ],
        nav: [
            {
                text: "Docs",
                link: "/",
                activeMatch:
                    "^/$|^/(quick-start|installation|configuration|persistence|replication|cluster|lua-scripting|pubsub|transactions|security)",
            },
            { text: "Commands", link: "/commands/", activeMatch: "/commands/" },
        ],
        sidebar: {
            "/": [
                {
                    text: "Getting Started",
                    items: [
                        { text: "Introduction", link: "/" },
                        { text: "Quick Start", link: "/quick-start" },
                        { text: "Installation", link: "/installation" },
                        { text: "Configuration", link: "/configuration" },
                    ],
                },
                {
                    text: "Core Concepts",
                    items: [
                        { text: "Persistence", link: "/persistence" },
                        { text: "Replication", link: "/replication" },
                        { text: "Cluster Mode", link: "/cluster" },
                    ],
                },
                {
                    text: "Advanced",
                    items: [
                        { text: "Lua Scripting", link: "/lua-scripting" },
                        { text: "Pub/Sub", link: "/pubsub" },
                        { text: "Transactions", link: "/transactions" },
                        { text: "Security", link: "/security" },
                    ],
                },
            ],
            "/commands/": commandSidebar,
            "/api/": [
                {
                    text: "REST API",
                    items: [
                        { text: "Overview", link: "/api/" },
                        { text: "Authentication", link: "/api/auth" },
                        { text: "Endpoints", link: "/api/endpoints" },
                    ],
                },
            ],
        },
        editLink: {
            docRepoBaseUrl:
                "https://github.com/1jmdev/BetterKV/tree/main/www/docs/pages",
        },
        lastUpdated: true,
    },
    markdown: {
        showLineNumbers: true,
    },
});
